# syntax=docker/dockerfile:1
FROM ruby:2.7.4-bullseye
WORKDIR '/diamantes'

EXPOSE 3000

# Add a script to be executed every time the container starts.
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]

